import "./Skills.css";
import "./Youtube.css";
import "./Blog.css";
import "./globals.css";
import "./zero.css";
import "./Footer.css";
import "./Contact.css";
import "./Header.css";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Thushan vithana",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
